name: my first actions

on: [push]

jobs:
  builds:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: run calculator
      run: |
        cd src
        python calculator.py
